package GUI;

import Classes.Coelhos;
import DAO.ErpDAOException;
import DAO.CoelhosDAO;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

public class AlteraCoelho extends javax.swing.JFrame {

    private Coelhos M = new Coelhos();
    int id, posicao;
    private static ArrayList<Coelhos> coelho = new ArrayList<Coelhos>();

    /**
     * Creates new form AlteraMedico
     */
    public AlteraCoelho() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RBF = new javax.swing.JRadioButton();
        RBM = new javax.swing.JRadioButton();
        ESP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NASC = new javax.swing.JTextField();
        PES = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        OK = new javax.swing.JButton();
        CAN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        N = new javax.swing.JTextField();
        COMBO = new javax.swing.JComboBox<>();
        COR = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        RBF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RBF.setText("Feminino");
        RBF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBFActionPerformed(evt);
            }
        });

        RBM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RBM.setText("Masculino");
        RBM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBMActionPerformed(evt);
            }
        });

        ESP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ESP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ESPActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Raça:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Data de Nascimento:");

        NASC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NASC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NASCActionPerformed(evt);
            }
        });

        PES.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PESActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Peso:");

        OK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        OK.setText("OK");
        OK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OKMouseClicked(evt);
            }
        });

        CAN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CAN.setText("cancelar");
        CAN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CANMouseClicked(evt);
            }
        });
        CAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Sexo:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nome:");

        N.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NActionPerformed(evt);
            }
        });

        COMBO.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        COMBO.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                COMBOItemStateChanged(evt);
            }
        });

        COR.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        COR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CORActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Cor:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NASC, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PES, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                                .addComponent(CAN, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(RBM)
                                .addGap(102, 102, 102)
                                .addComponent(RBF))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(N, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(COMBO, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(ESP, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(215, 215, 215))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(COR, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(OK, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(COMBO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBM)
                    .addComponent(RBF))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ESP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(NASC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addComponent(CAN))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OK)
                    .addComponent(COR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(31, 31, 31))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NASCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NASCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NASCActionPerformed

    private void PESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PESActionPerformed

    private void OKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OKMouseClicked
        Coelhos M = new Coelhos();
        Date dataNasc = null;
        char sexo = ' ';
        DateFormat dtOutput = new SimpleDateFormat("dd/MM/yyyy");
        M.setID_coelho(id);
        if (N.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "O Campo nome não pode estar vazio");
        } else {

            M.setNome(N.getText());
            M.setRaca(ESP.getText());
            if (RBF.isSelected() == true) {
                sexo = 'F';
            }
            if (RBM.isSelected() == true) {
                sexo = 'M';
            }
            M.setSexo(sexo);
            if (NASC.getText().equals("")) {
                dataNasc = null;
            } else {
                try {
                    dataNasc = dtOutput.parse(NASC.getText());
                } catch (ParseException ex) {
                    System.out.println("Erro na conversão da data");
                }
            }
            M.setData_nasc(dataNasc);
            try {
                float peso = Float.parseFloat(PES.getText());
                M.setPeso(peso);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Formato inválido: " + PES.getText());
            }

            M.setCor(COR.getText());

            CoelhosDAO PDAO = new CoelhosDAO();
            PDAO.atualizar(M);
            JOptionPane.showMessageDialog(rootPane, "Atualização efetuada com sucesso!!");
            dispose();
        }
    }//GEN-LAST:event_OKMouseClicked

    private void CANMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CANMouseClicked
        dispose();
    }//GEN-LAST:event_CANMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        carregaCombo();
        carrega();
    }//GEN-LAST:event_formComponentShown

    private void RBMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBMActionPerformed
        if (RBF.isSelected()) {
            RBF.setSelected(false);
        }
    }//GEN-LAST:event_RBMActionPerformed

    private void RBFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBFActionPerformed
        if (RBM.isSelected()) {
            RBM.setSelected(false);
        }
    }//GEN-LAST:event_RBFActionPerformed

    private void ESPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ESPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ESPActionPerformed

    private void CANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CANActionPerformed

    private void NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NActionPerformed

    private void COMBOItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_COMBOItemStateChanged
        posicao = (int) COMBO.getSelectedIndex();
        id = coelho.get(posicao).getID_coelho();
        carrega();
    }//GEN-LAST:event_COMBOItemStateChanged

    private void CORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CORActionPerformed
    public static void carregaCombo() {
        COMBO.removeAllItems();
        CoelhosDAO MDAO = new CoelhosDAO();
        coelho = MDAO.listar();
        for (int i = 0; i < coelho.size(); i++) {
            COMBO.addItem(coelho.get(i).getNome());
        }
    }

    public void carrega() {
        CoelhosDAO MDAO = new CoelhosDAO();
        M = MDAO.procurar(id);
        N.setText(M.getNome());
        ESP.setText(M.getRaca());

        // Clear previous selections
        RBF.setSelected(false);
        RBM.setSelected(false);

        // Set the correct selection based on the value from M
        if (M.getSexo() == 'F') {
            RBF.setSelected(true);
        } else if (M.getSexo() == 'M') {
            RBM.setSelected(true);
        }

        if (M.getData_nasc() == null) {
            NASC.setText("");
        } else {
            Date dn = M.getData_nasc();
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            NASC.setText(sdf.format(dn));
        }

        PES.setText(String.format("%.2f", M.getPeso()));
        COR.setText(M.getCor());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CAN;
    private static javax.swing.JComboBox<String> COMBO;
    private javax.swing.JTextField COR;
    private javax.swing.JTextField ESP;
    private javax.swing.JTextField N;
    private javax.swing.JTextField NASC;
    private javax.swing.JButton OK;
    private javax.swing.JTextField PES;
    private javax.swing.JRadioButton RBF;
    private javax.swing.JRadioButton RBM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
