package GUI;

import Classes.Coelhos;
import Classes.Crias;
import Classes.CriasCoelhos;
import DAO.ErpDAOException;
import DAO.CriasDAO;
import DAO.CoelhosDAO;
import DAO.CriasCoelhosDAO;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 278033
 */
public class AlteraCria extends javax.swing.JFrame {

    private static ArrayList<Coelhos> Pai = new ArrayList<Coelhos>();
    private static ArrayList<Coelhos> Mae = new ArrayList<Coelhos>();
    private Crias C = new Crias();
    private CriasCoelhos M = new CriasCoelhos();
    private CriasCoelhos PC = new CriasCoelhos();
    CriasDAO CDAO2 = new CriasDAO();
    //Colocar dentro do codigo o id da consulta vindo da outra janela!!!
    int codigo;
    int idmae, idpai;

    /**
     * Creates new form AlteraConsulta
     */
    public AlteraCria(int cod) {
        codigo = cod;
        initComponents();
    }

    AlteraCria() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Paibox = new javax.swing.JComboBox<>();
        Maebox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Datafield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Pesofield = new javax.swing.JTextField();
        Cancelar = new javax.swing.JButton();
        Alterar = new javax.swing.JButton();
        RBM = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        RBF = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Pai");

        jLabel2.setText("Mãe");

        Paibox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                PaiboxItemStateChanged(evt);
            }
        });

        Maebox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MaeboxItemStateChanged(evt);
            }
        });

        jLabel3.setText("Data de nascimento");

        Datafield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatafieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Peso ao nascer");

        Pesofield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesofieldActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelarMouseClicked(evt);
            }
        });

        Alterar.setText("Alterar");
        Alterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AlterarMouseClicked(evt);
            }
        });

        RBM.setText("Masculino");
        RBM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBMActionPerformed(evt);
            }
        });

        jLabel5.setText("Sexo:");

        RBF.setText("Feminino");
        RBF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Alterar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RBF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RBM)))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Maebox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Paibox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Datafield)
                    .addComponent(Pesofield, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Paibox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Maebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Datafield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Pesofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBF)
                    .addComponent(RBM))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancelar)
                    .addComponent(Alterar))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DatafieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatafieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DatafieldActionPerformed

    private void PesofieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesofieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PesofieldActionPerformed

    private void MaeboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MaeboxItemStateChanged
        posicaop = (int) Maebox.getSelectedIndex();
        idmae = Mae.get(posicaop).getID_coelho();
    }//GEN-LAST:event_MaeboxItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        carregaCombo();

        carregaComboCoelhos();
        try {

            C = CDAO2.procurar(codigo);
            CriasCoelhosDAO MCDAO = new CriasCoelhosDAO();
            M = MCDAO.procuraPai(codigo);
            CriasCoelhosDAO PCDAO = new CriasCoelhosDAO();
            PC = PCDAO.procuraMae(codigo);

            Paibox.setSelectedItem(M.getNome_pai());
            Maebox.setSelectedItem(PC.getNome_mae());
            
            float peso = C.getPeso_nasc();
            
            Pesofield.setText(String.valueOf(peso));
        } catch (ErpDAOException ex) {
            System.out.println("Falha na locaização");
        }
        DateFormat formato = new SimpleDateFormat("HH:mm:ss");
        if (C.getData_cria() == null) {
            Datafield.setText("");
        } else {
            Date dn = null;
            String aux = "";
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

            dn = C.getData_cria();
            aux = sdf.format(dn);

            Datafield.setText(aux);
            
        }
        char sexo = C.getSexo_cria();
        if (sexo == 'F') {
            RBF.setSelected(true);
        } else if (sexo == 'M') {
            RBM.setSelected(true);
        }
    }//GEN-LAST:event_formWindowOpened

    private void AlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlterarMouseClicked
        DateFormat dtOutput = new SimpleDateFormat("dd/MM/yyyy");
        float peso = 0;
        peso = (Float.parseFloat(Pesofield.getText()));
        Date data = null;
        try {
            data = dtOutput.parse(Datafield.getText());
        } catch (ParseException ex) {
            System.out.println("Erro na conversão da data");
        }
        char sexo = ' ';
        if (RBF.isSelected() == true) {
            sexo = 'F';
        }
        if (RBM.isSelected() == true) {
            sexo = 'M';
        }
        C.setSexo_cria(sexo);
        C.setID_cria(codigo);
        C.setID_mae(idmae);
        C.setID_pai(idpai);
        C.setData_cria(data);
        C.setPeso_nasc(peso);

        try {
            CDAO2.atualizar(C);
            JOptionPane.showMessageDialog(null, "Alteração concluída");

        } catch (ErpDAOException ex) {
            Logger.getLogger(AlteraCria.class
                    .getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro na Alteração");
        }
        dispose();
    }//GEN-LAST:event_AlterarMouseClicked

    private void CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarMouseClicked
        dispose();
    }//GEN-LAST:event_CancelarMouseClicked

    private void RBMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBMActionPerformed
        if (RBF.isSelected()) {
            RBF.setSelected(false);
        }
    }//GEN-LAST:event_RBMActionPerformed

    private void RBFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBFActionPerformed
        if (RBM.isSelected()) {
            RBM.setSelected(false);
        }
    }//GEN-LAST:event_RBFActionPerformed

    private void PaiboxItemStateChanged(java.awt.event.ItemEvent evt) {

        posicao = (int) Paibox.getSelectedIndex();
        idpai = Pai.get(posicao).getID_coelho();

    }

    public static void carregaData() {
        Date data = null;
        DateFormat dtOutput = new SimpleDateFormat("dd/MM/yyyy");
    }

    public static void carregaCombo() {
        Paibox.removeAllItems();
        CoelhosDAO MDAO = new CoelhosDAO();
        Pai = MDAO.listar();

        for (int i = 0; i < Pai.size(); i++) {
            Paibox.addItem(Pai.get(i).getNome());

        }
    }

    public static void carregaComboCoelhos() {
        Maebox.removeAllItems();
        CoelhosDAO PDAO = new CoelhosDAO();
        Mae = PDAO.listar();

        for (int i = 0; i < Mae.size(); i++) {
            Maebox.addItem(Mae.get(i).getNome());

        }
    }

    int posicaop;
    int posicao;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alterar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JTextField Datafield;
    private static javax.swing.JComboBox<String> Maebox;
    private static javax.swing.JComboBox<String> Paibox;
    private javax.swing.JTextField Pesofield;
    private javax.swing.JRadioButton RBF;
    private javax.swing.JRadioButton RBM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

}
