/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.Coelhos;
import Classes.Proprietarios;
import Classes.Vendas;
import Classes.VendasCC;
import DAO.ErpDAOException;
import DAO.CoelhosDAO;
import DAO.VendasCCDAO;
import DAO.VendasDAO;
import DAO.ProprietariosDAO;
import static java.lang.String.format;
import static java.lang.String.format;
import static java.lang.String.format;
import java.sql.SQLException;
import java.sql.Time;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author 278033
 */
public class AlteraVendas extends javax.swing.JFrame {

    private static ArrayList<Coelhos> buns = new ArrayList<Coelhos>();
    private static ArrayList<Proprietarios> props = new ArrayList<Proprietarios>();
    private Vendas C = new Vendas();
    private Coelhos M = new Coelhos();
    private Proprietarios PC = new Proprietarios();
    VendasDAO CDAO2 = new VendasDAO();
    //Colocar dentro do codigo o id da consulta vindo da outra janela!!!
    int codigo;
    int idpac, idmed;

    /**
     * Creates new form AlteraConsulta
     */
    public AlteraVendas(int cod) {
        codigo = cod;
        initComponents();
    }

    AlteraVendas() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Coelhosbox = new javax.swing.JComboBox<>();
        Proprietariosbox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Datafield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Precofield = new javax.swing.JTextField();
        Cancelar = new javax.swing.JButton();
        Alterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Coelho");

        jLabel2.setText("Comprador");

        Coelhosbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CoelhosboxItemStateChanged(evt);
            }
        });

        Proprietariosbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ProprietariosboxItemStateChanged(evt);
            }
        });

        jLabel3.setText("Data");

        Datafield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatafieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Preço");

        Precofield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecofieldActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelarMouseClicked(evt);
            }
        });

        Alterar.setText("Alterar");
        Alterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AlterarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(Cancelar))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Proprietariosbox, 0, 185, Short.MAX_VALUE)
                    .addComponent(Coelhosbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Datafield)
                    .addComponent(Precofield)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Alterar)
                        .addGap(11, 11, 11)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Coelhosbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Proprietariosbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Datafield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Precofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancelar)
                    .addComponent(Alterar))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DatafieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatafieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DatafieldActionPerformed

    private void PrecofieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecofieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecofieldActionPerformed

    private void ProprietariosboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ProprietariosboxItemStateChanged
        posicaop = Proprietariosbox.getSelectedIndex();
        if (posicaop >= 0 && posicaop < props.size()) {
            idpac = props.get(posicaop).getID_prop();
        }
    }//GEN-LAST:event_ProprietariosboxItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        carregaCombo();
        carregaComboProprietarios();

        // Load sale data
        C = CDAO2.procurar(codigo);
        CoelhosDAO MCDAO = new CoelhosDAO();
        M = MCDAO.procurar(C.getID_coelho());
        ProprietariosDAO PCDAO = new ProprietariosDAO();
        PC = PCDAO.procurar(C.getID_comprador());

        // Set the selected items in ComboBoxes
        Coelhosbox.setSelectedItem(M.getNome());
        Proprietariosbox.setSelectedItem(PC.getNome_prop());

        // Set the date and price fields
        DateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        if (C.getData_venda() == null) {
            Datafield.setText("");
        } else {
            String aux = sdf.format(C.getData_venda());
            Datafield.setText(aux);
        }
        Precofield.setText(String.valueOf(C.getPreco()));
    }//GEN-LAST:event_formWindowOpened

    private void AlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlterarMouseClicked
        DateFormat dtOutput = new SimpleDateFormat("dd/MM/yyyy");
        Date data = null;
        try {
            data = dtOutput.parse(Datafield.getText());
        } catch (ParseException ex) {
            System.out.println("Erro na conversão da data");
        }

        float price = Float.parseFloat(Precofield.getText());
        C.setPreco(price);
        C.setData_venda(data);

        // Set the new IDs for coelho and comprador
        C.setID_venda(codigo);
        C.setID_comprador(idpac);
        C.setID_coelho(idmed);

        VendasCCDAO vendasDAO = new VendasCCDAO();
        try {
            vendasDAO.atualizar(C);
        } catch (SQLException ex) {
            Logger.getLogger(AlteraVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Alteração concluída");
        dispose();
    }//GEN-LAST:event_AlterarMouseClicked

    private void CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarMouseClicked
        dispose();
    }//GEN-LAST:event_CancelarMouseClicked

    private void CoelhosboxItemStateChanged(java.awt.event.ItemEvent evt) {
        posicao = Coelhosbox.getSelectedIndex();
        if (posicao >= 0 && posicao < buns.size()) {
            idmed = buns.get(posicao).getID_coelho();
        }
    }

    public static void carregaData() {
        Date data = null;
        DateFormat dtOutput = new SimpleDateFormat("dd/MM/yyyy");
    }

    public static void carregaCombo() {
        Coelhosbox.removeAllItems();
        CoelhosDAO MDAO = new CoelhosDAO();
        buns = MDAO.listar();

        for (int i = 0; i < buns.size(); i++) {
            Coelhosbox.addItem(buns.get(i).getNome());

        }
    }

    public static void carregaComboProprietarios() {
        Proprietariosbox.removeAllItems();
        ProprietariosDAO PDAO = new ProprietariosDAO();
        props = PDAO.listar();

        for (int i = 0; i < props.size(); i++) {
            Proprietariosbox.addItem(props.get(i).getNome_prop());

        }
    }

    int posicaop;
    int posicao;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alterar;
    private javax.swing.JButton Cancelar;
    private static javax.swing.JComboBox<String> Coelhosbox;
    private javax.swing.JTextField Datafield;
    private javax.swing.JTextField Precofield;
    private static javax.swing.JComboBox<String> Proprietariosbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

}
