/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.Coelhos;
import Classes.Proprietarios;
import Classes.Vendas;
import DAO.ErpDAOException;
import DAO.CoelhosDAO;
import DAO.VendasDAO;
import DAO.ProprietariosDAO;
import static java.lang.String.format;
import java.sql.Time;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author Juliana
 */
public class EfetVenda extends javax.swing.JFrame {

    private static ArrayList<Proprietarios> prop = new ArrayList<Proprietarios>();
    private static ArrayList<Coelhos> bun = new ArrayList<Coelhos>();
    private static ArrayList<Vendas> venda = new ArrayList<Vendas>();
    private static int posiMed, posiPac;
    private static int idpac,idmed;
    public EfetVenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog2 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog3 = new datechooser.beans.DateChooserDialog();
        CB_bun = new javax.swing.JComboBox();
        CB_prop = new javax.swing.JComboBox();
        BT_confirmar = new javax.swing.JButton();
        DC = new datechooser.beans.DateChooserPanel();
        TF_hora = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BT_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        CB_bun.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CB_bun.setToolTipText("");
        CB_bun.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_bunItemStateChanged(evt);
            }
        });

        CB_prop.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CB_prop.setToolTipText("");
        CB_prop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_propItemStateChanged(evt);
            }
        });

        BT_confirmar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BT_confirmar.setText("OK");
        BT_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_confirmarActionPerformed(evt);
            }
        });

        DC.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
            public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
                DCOnSelectionChange(evt);
            }
        });

        TF_hora.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TF_hora.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Preço (formato: 0000.00)");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Coelho");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Comprador");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Data");

        BT_cancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BT_cancelar.setText("CANCELAR");
        BT_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(26, 26, 26))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CB_bun, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CB_prop, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(BT_cancelar)
                                .addGap(110, 110, 110)
                                .addComponent(BT_confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 129, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(TF_hora))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1)
                                        .addGap(15, 15, 15)))))))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CB_bun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CB_prop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TF_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel4)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_cancelar)
                    .addComponent(BT_confirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CB_bunItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_bunItemStateChanged
        posiMed = (int) CB_bun.getSelectedIndex();
        idmed = bun.get(posiMed).getID_coelho();
    }//GEN-LAST:event_CB_bunItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        carregaComboCoelhos();
        carregaComboProprietarios();
    }//GEN-LAST:event_formWindowOpened

    private void BT_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_confirmarActionPerformed
        int mes = 0;    
        VendasDAO pdao = new VendasDAO();
            Vendas C = new Vendas();
            Calendar date = DC.getSelectedDate();
            
            C.setID_coelho(idmed);
            C.setID_comprador(idpac);
            mes = date.get(Calendar.MONTH) + 1;
            String datas = (date.get(Calendar.DAY_OF_MONTH) + "/" + mes + "/" + date.get(Calendar.YEAR));
            DateFormat dtOutput = new SimpleDateFormat("dd/MM/yyyy");
        try {
            Date data = dtOutput.parse(datas);
            C.setData_venda(data);
        } catch (ParseException ex) {
            Logger.getLogger(EfetVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        float preco = Float.parseFloat(TF_hora.getText());
        C.setPreco(preco);
            
        pdao.inserir(C);
        dispose();  
    }//GEN-LAST:event_BT_confirmarActionPerformed

    private void CB_propItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_propItemStateChanged
        posiPac = (int) CB_prop.getSelectedIndex();
        idpac = prop.get(posiPac).getID_prop();
        //T.setText(posiPac+"");
    }//GEN-LAST:event_CB_propItemStateChanged

    private void DCOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_DCOnSelectionChange

    }//GEN-LAST:event_DCOnSelectionChange

    private void BT_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_BT_cancelarActionPerformed
    
    public static void carregaComboProprietarios() {
            CB_prop.removeAllItems();
            ProprietariosDAO PDAO = new ProprietariosDAO();
            prop = PDAO.listar();

            for (int i = 0; i < prop.size(); i++) {
            CB_prop.addItem(prop.get(i).getNome_prop());

        }
    }
    
    public static void carregaComboCoelhos() {
        //try {
            CB_bun.removeAllItems();
            CoelhosDAO MDAO = new CoelhosDAO();
            bun = MDAO.listar();
        //} catch (ErpDAOException ex) {
           // System.out.println("problema");
       // }

        for (int i = 0; i < bun.size(); i++) {
            CB_bun.addItem(bun.get(i).getNome());

        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_cancelar;
    private javax.swing.JButton BT_confirmar;
    private static javax.swing.JComboBox CB_bun;
    private static javax.swing.JComboBox CB_prop;
    private datechooser.beans.DateChooserPanel DC;
    private javax.swing.JTextField TF_hora;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private datechooser.beans.DateChooserDialog dateChooserDialog2;
    private datechooser.beans.DateChooserDialog dateChooserDialog3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    private JTextArea setString(String date) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
