/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.Coelhos;
import Classes.Crias;
import DAO.ErpDAOException;
import DAO.CriasDAO;
import DAO.CoelhosDAO;
import static java.lang.String.format;
import java.sql.Time;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author Juliana
 */
public class InsereCria extends javax.swing.JFrame {

    private static ArrayList<Coelhos> pai = new ArrayList<Coelhos>();
    private static ArrayList<Coelhos> mae = new ArrayList<Coelhos>();
    private static ArrayList<Crias> cria = new ArrayList<Crias>();
    private static int posiMae, posiPai;
    private static int idpai, idmae;

    public InsereCria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog2 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog3 = new datechooser.beans.DateChooserDialog();
        CB_mae = new javax.swing.JComboBox();
        CB_pai = new javax.swing.JComboBox();
        BT_confirmar = new javax.swing.JButton();
        DC = new datechooser.beans.DateChooserPanel();
        TF_hora = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BT_cancelar = new javax.swing.JButton();
        RBM = new javax.swing.JRadioButton();
        RBF = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        CB_mae.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CB_mae.setToolTipText("");
        CB_mae.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_maeItemStateChanged(evt);
            }
        });

        CB_pai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CB_pai.setToolTipText("");
        CB_pai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_paiItemStateChanged(evt);
            }
        });

        BT_confirmar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BT_confirmar.setText("OK");
        BT_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_confirmarActionPerformed(evt);
            }
        });

        DC.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
            public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
                DCOnSelectionChange(evt);
            }
        });

        TF_hora.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TF_hora.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Peso (kg)");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mãe");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Pai");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Data de nascimento:");

        BT_cancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BT_cancelar.setText("CANCELAR");
        BT_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_cancelarActionPerformed(evt);
            }
        });

        RBM.setText("Masculino");
        RBM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBMActionPerformed(evt);
            }
        });

        RBF.setText("Feminino");
        RBF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBFActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Sexo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(DC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TF_hora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(77, 77, 77))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(RBM, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RBF))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(BT_cancelar)
                        .addGap(110, 110, 110)
                        .addComponent(BT_confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel3))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CB_mae, 0, 480, Short.MAX_VALUE)
                            .addComponent(CB_pai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CB_mae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CB_pai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TF_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RBM)
                                    .addComponent(RBF)))
                            .addComponent(DC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_cancelar)
                    .addComponent(BT_confirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CB_maeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_maeItemStateChanged
        posiMae = (int) CB_mae.getSelectedIndex();
        idmae = mae.get(posiMae).getID_coelho();
    }//GEN-LAST:event_CB_maeItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        carregaComboMae();
        carregaComboPai();
    }//GEN-LAST:event_formWindowOpened

    private void BT_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_confirmarActionPerformed
        int mes = 0;
        CriasDAO pdao = new CriasDAO();
        Crias C = new Crias();
        Calendar date = DC.getSelectedDate();

        C.setID_mae(idmae);
        C.setID_pai(idpai);
        mes = date.get(Calendar.MONTH) + 1;
        String datas = (date.get(Calendar.DAY_OF_MONTH) + "/" + mes + "/" + date.get(Calendar.YEAR));
        DateFormat dtOutput = new SimpleDateFormat("dd/MM/yyyy");
        try {
            Date data = dtOutput.parse(datas);
            C.setData_cria(data);
        } catch (ParseException ex) {
            Logger.getLogger(InsereCria.class.getName()).log(Level.SEVERE, null, ex);
        }
        String hora = TF_hora.getText();
        SimpleDateFormat format = new SimpleDateFormat("HH:mm:ss");
        float peso;
        try {
            peso = Float.valueOf(format.parse(hora).getTime());
            C.setPeso_nasc(peso);
        } catch (ParseException ex) {
            Logger.getLogger(InsereCria.class.getName()).log(Level.SEVERE, null, ex);
        }
        char sexo;
        if (RBF.isSelected() == true) {
            sexo = 'F';
        }
        if (RBM.isSelected() == true) {
            sexo = 'M';
        }

        try {
            pdao.inserir(C);
        } catch (ErpDAOException ex) {
            Logger.getLogger(InsereCria.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_BT_confirmarActionPerformed

    private void CB_paiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_paiItemStateChanged
        posiPai = (int) CB_pai.getSelectedIndex();
        idpai = pai.get(posiPai).getID_coelho();
        //T.setText(posiPai+"");
    }//GEN-LAST:event_CB_paiItemStateChanged

    private void DCOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_DCOnSelectionChange

    }//GEN-LAST:event_DCOnSelectionChange

    private void BT_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_BT_cancelarActionPerformed

    private void RBMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBMActionPerformed
        if (RBF.isSelected()) {
            RBF.setSelected(false);
        }
    }//GEN-LAST:event_RBMActionPerformed

    private void RBFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBFActionPerformed
        if (RBM.isSelected()) {
            RBM.setSelected(false);
        }
    }//GEN-LAST:event_RBFActionPerformed

    public static void carregaComboPai() {
        CB_pai.removeAllItems();
        CoelhosDAO PDAO = new CoelhosDAO();
        pai = PDAO.listar();

        for (int i = 0; i < pai.size(); i++) {
            CB_pai.addItem(pai.get(i).getNome());

        }
    }

    public static void carregaComboMae() {
        //try {
        CB_mae.removeAllItems();
        CoelhosDAO MDAO = new CoelhosDAO();
        mae = MDAO.listar();
        //} catch (ErpDAOException ex) {
        // System.out.println("problema");
        // }

        for (int i = 0; i < mae.size(); i++) {
            CB_mae.addItem(mae.get(i).getNome());

        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_cancelar;
    private javax.swing.JButton BT_confirmar;
    private static javax.swing.JComboBox CB_mae;
    private static javax.swing.JComboBox CB_pai;
    private datechooser.beans.DateChooserPanel DC;
    private javax.swing.JRadioButton RBF;
    private javax.swing.JRadioButton RBM;
    private javax.swing.JTextField TF_hora;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private datechooser.beans.DateChooserDialog dateChooserDialog2;
    private datechooser.beans.DateChooserDialog dateChooserDialog3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

    private JTextArea setString(String date) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
